In [1]:
from feature_manager import FeatureManager
from PIL import Image
import numpy as np
from os import walk
from matplotlib.colors import rgb_to_hsv
from pprint import pprint

def load_image(fn):
    img = Image.open(f'./feature-engineering-test-files/{fn}')
    img.load()
    data = np.asarray(img, dtype="int32")
    return data

In [2]:
wk = tuple(walk("./feature-engineering-test-files"))[0]

for fn in wk[2]:
    if '-m.jpg' in fn:
        mask_im = load_image(fn)
        im = load_image(fn.replace("-m.jpg", ".jpg"))
        features = {"color_features": ["HistogramHSV"]}
        # features = None
        # features = {"geometric_features": ["Area", "Perimeter"]}
        fm = FeatureManager(image=im, mask_image=mask_im, feature_dict=features)
        pprint(fm())

{'color_features': {'HistogramHSV': (array([163, 159, 121, 153, 124,  95, 198, 660, 607, 220]),
                                     array([ 22. ,  45.9,  69.8,  93.7, 117.6, 141.5, 165.4, 189.3, 213.2,
       237.1, 261. ]))}}
{'color_features': {'HistogramHSV': (array([129, 167, 110, 235, 142,  82, 110, 381, 664, 480]),
                                     array([ 27. ,  50.4,  73.8,  97.2, 120.6, 144. , 167.4, 190.8, 214.2,
       237.6, 261. ]))}}
{'color_features': {'HistogramHSV': (array([193, 390, 229, 298, 373, 440, 195,  96, 139, 147]),
                                     array([ 26. ,  48.9,  71.8,  94.7, 117.6, 140.5, 163.4, 186.3, 209.2,
       232.1, 255. ]))}}
{'color_features': {'HistogramHSV': (array([224, 321, 228, 211, 114, 106, 201, 258, 440, 397]),
                                     array([ 25. ,  48.6,  72.2,  95.8, 119.4, 143. , 166.6, 190.2, 213.8,
       237.4, 261. ]))}}
{'color_features': {'HistogramHSV': (array([185, 181, 144, 207, 140, 206, 400, 533, 340,